language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
  - bash <(curl -s https://codecov.io/bash)
